version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: todo_database
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=testing
      - MYSQL_DATABASE=todo

    ports:
      - "3306:3306"

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
