version: '3.3'

services:

  database:
    build: ./database
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=testing
      - MYSQL_DATABASE=todo
    volumes:
      - database:/var/lib/mysql


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always

volumes:
  database: