version: '3.8'
name: 'todo'

services:

  database:
    build: ./database
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=testing
      - MYSQL_DATABASE=todo
    volumes:
      - database:/var/lib/mysql
    networks:
      - app

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - app
      - web

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app

volumes:
  database:

networks:
  app:
    internal: true
  web:
    driver: bridge