version: '3.8'
name: todoApplication

services:
  backend:
    image: christophknuchelwiss/todo-backend:latest
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: christophknuchelwiss/todo-frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  database:
    image: christophknuchelwiss/todo-database:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
