name: Publish Docker image to Docker Hub

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Frontend
        uses: docker/build-push-action@v3
        with:
          context: ./Sidequests/SQ8/frontend
          file: ./Sidequests/SQ8/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v3
        with:
          context: ./Sidequests/SQ8/backend
          file: ./Sidequests/SQ8/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Push Docker Compose
        run: |
          docker-compose -f ./Sidequests/SQ8/docker-compose.yml config
          docker-compose -f ./Sidequests/SQ8/docker-compose.yml push
