name: Publish Docker image to Docker Hub

on:
    release:
      types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - 
              name: Checkout repository
              uses: actions/checkout@v3

            -
              name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Build and push
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: ./Sidequests/SQ8/compose.yml
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/sq8-todoapplication:latest