name: Run Vite Tests

on:
  push:
    branches: 
      - main
      - Feature/*
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd Sidequests/SQ2A/M324_PROJEKT_TODOLIST/frontend
          npm install

      - name: Run tests
        run: |
          cd Sidequests/SQ2A/M324_PROJEKT_TODOLIST/frontend
          npm run test

  build_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd Sidequests/SQ2A/M324_PROJEKT_TODOLIST/frontend
          npm install

      - name: Run tests
        run: |
          cd Sidequests/SQ2A/M324_PROJEKT_TODOLIST/frontend
          npm run test

      - name: Build
        run: |
          cd Sidequests/SQ2A/M324_PROJEKT_TODOLIST/frontend
          npm run build
